import Head from 'next/head'
import SearchBar from '@/components/SearchBar';
import Header from '@/components/Header';
import Image from 'next/image';
import Link from 'next/link';
import Footer from '@/components/Footer';

export default function Home () {

  return (
    <div className='bg-slate-900 min-h-screen flex flex-col'>
      <Head>
        <title>Luster</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <Header />
      <main className='flex-grow flex flex-col items-center justify-center py-4'>
        <section className='flex flex-col-reverse md:flex-row items-center justify-between w-4/5'>
          <div className='md:w-2/4 h-full gap-4 md:gap-12 flex flex-col justify-between'>
            <div>
              <h1 className='text-center md:text-start text-slate-50 text-3xl md:text-5xl italic mb-4'>Luster</h1>
              <p className='md:text-xl mb-2 text-slate-100'>Free images created by AI. Luster provides assets created by the community using an AI to use in your personal projects or wherever you want.</p>
              <p className='md:text-xl mb-4 text-slate-100'>Or you can get inspired to make your own prompts based in our resources.</p>
              <SearchBar />
            </div>
            <div>
              <p className='text-slate-300 italic'>The images are provided by users of the community, you can make your contribution uploading any image created using an AI clicking <Link href='/upload' className='underline'>here</Link>.</p>
            </div>
          </div>
          <div className='rounded-xl overflow-hidden md:w-96'>
            <Image src='https://res.cloudinary.com/dfyxdowwb/image/upload/v1678098129/my-public-folder/ss4as8ow7rcn7qfrzpoj.png' alt='Eagle generated by AI' width={400} height={400} />
          </div>
        </section>
      </main>
      <Footer />
    </div>
  )
}
